### ISSUE TITLE
About the additional STOP cmd

### ISSUE THREAD

**Issue by WPH-commit** [dotchen/LAV#11]
https://github.com/dotchen/LAV/blob/db2af575840ef390b65441b0970e72e88c4b05c1/lav/utils/datasets/bev_dataset.py#L54
Hi, do we override the ChangeLaneRight command with this additional Stop command here?

**Comment by dotchen** [comment]
Thanks for reporting this. I have fixed this in the repo. The stop command was an experimental feature we later found to hurt the performance. Closing the issue.
