### ISSUE TITLE
How can I visualize the results?

### ISSUE THREAD

**Issue by kevinchiu19** [dotchen/LAV#13]
Thanks to the author for the wonderful code!
I would like to ask how to visualize the results of the network output, for example: RGB camera inputs, predicted road geometries, and detection and motion predictions respectively. 

Looking forward to your reply, thank you very much!

**Comment by dotchen** [comment]
Thank you very much for your interest in our project.

You may use the visualization function here: https://github.com/dotchen/LAV/blob/a63af0999c2d696f5596060131a22087140044f2/lav/utils/logger.py#L94-L162

It overlays object detection, road segmentation and motion predictions in the visualization.

**Comment by kevinchiu19** [comment]
Thank you for your reply！

Sorry I'm not very familiar with wandb, what is 'it' and 'opt_info'?
Are there any examples to refer to?

**Comment by kevinchiu19** [comment]
I just want to get the visualization like in the video (https://www.youtube.com/watch?v=-TlxbmSQ7rQ), the 'Predicted map' and 'Predicted traffic & planning'. Can I visualize it without using wandb?

**Comment by kevinchiu19** [comment]
Thank you for your patient reply. 
With this example, I can understand it immediately. Thank you very much!

**Comment by wanghuai1994** [comment]
It's a wonderful job, this issue also inspires me a lot , but I still can't use provided "leaderboard_evaluator.py" in project with pre-trained weights and method proposed above to visualize  the results of the network output, just like the video in  "https://www.bilibili.com/video/BV1V34y1b7du". Could you give me some detailed instructions, thanks.
