### ISSUE TITLE
Is locs[0] equivalent to ego_locs?

### ISSUE THREAD

**Issue by KP-Zhang** [dotchen/LAV#28]
Hello,
Thank you for your wonderful work.

When reading your code, I find that in [temporal_lidar_painted_dataset.py](https://github.com/dotchen/LAV/blob/main/lav/utils/datasets/temporal_lidar_painted_dataset.py) locs[0] is equal to ego_locs. While, in [temporal_bev_dataset.py](https://github.com/dotchen/LAV/blob/main/lav/utils/datasets/temporal_bev_dataset.py),  locs[0] is different from ego_locs. The disagreement caused by 
ego_locs = rotate_points(ego_locs, -angle, ego_locs[0]) + [offset/self.pixels_per_meter, 0]
After rotating ego_locs, ego_locs[0] has already been changed, which will affect the following line.
locs = rotate_points(locs, -angle, ego_locs[0]) + [offset/self.pixels_per_meter, 0]
Is locs[0] supposed to be equivalent to ego_locs?

Thank you for your time.

**Comment by dotchen** [comment]
Yes, they are supposed to be the same, thank you for the catch, I just fixed it in the repo.

The correct order follows the one in temporal_lidar_painted_dataset
