### ISSUE TITLE
Issues with runing

### ISSUE THREAD

**Issue by klaus99815** [dotchen/LAV#6]
Hello,

There is a problem that puzzles me. When running programs, the CPU looks strange.
![1648206065(1)](https://user-images.githubusercontent.com/101232999/160109029-919c86ae-0425-4f3e-9ff8-9d434d4df14e.png)
The number of running processes can reach 40! It makes the simulator no longer smooth and the system execution time longer.
![1648206518(1)](https://user-images.githubusercontent.com/101232999/160110123-87ed362b-977d-47e0-b813-ca007a428163.png)
![1648206930(1)](https://user-images.githubusercontent.com/101232999/160111135-d1f8132f-a003-4af6-9f9c-fdf24d323768.png)

I think my CPU can provide good support normally..

CPU: Intel® Xeon(R) CPU E5-2630 v4 @ 2.20GHz × 40 
GPU: NVIDIA GeForce RTX 2080 T

May I ask if anyone has encountered a situation similar to mine？
Any help will be appreciated!

**Comment by dotchen** [comment]
Hello,

CARLA (both the server and the client) is threaded and CPU heavy, so this is expected.
My setup has a slighter older Xeon + Titan pascal, and my sys/game time ratio is always around 0.15x.

Hope this helps.

**Comment by klaus99815** [comment]
> Hello,
> 
> CARLA (both the server and the client) is threaded and CPU heavy, so this is expected. My setup has a slighter older Xeon + Titan pascal, and my sys/game time ratio is always around 0.15x.
> 
> Hope this helps.

Thanks for the feedback!
Thank you again for your excellent work!

**Comment by Watson52** [comment]
> > Hello,
> > CARLA (both the server and the client) is threaded and CPU heavy, so this is expected. My setup has a slighter older Xeon + Titan pascal, and my sys/game time ratio is always around 0.15x.
> > Hope this helps.
> 
> Thanks for the feedback! Thank you again for your excellent work!

Hi,  @klaus99815 could you accelerate the evaluation? Or increase the ratio value. I also found it still have many available resources for CPU or memory of GPU.
